import Head from 'next/head'
import Image from 'next/image'
import PopularMovies from './components/PopularMovies'
import styles from '../styles/Home.module.css'
import LatestMovies from './components/LatestMovies'


export default function Home({popularMovies, latestMovies}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section_wrapper}>
          <div className={styles.title}>What&apos;s Popular?</div>
          <PopularMovies movieList={popularMovies} />
        </section>
        <section className={styles.section_wrapper}>
          <div className={styles.title}>What&apos;s Latest?</div>
          <LatestMovies movieList={latestMovies} />
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(){
  //I'm using .env.local NEXT_PUBLIC_API_URL=moviedbapikey
  const requestPopularMovies = await fetch(`${process.env.NEXT_PUBLIC_API_URL}3/movie/popular?api_key=${process.env.NEXT_PUBLIC_API_KEY}&language=en-US&page=1`);
  const requestLatestMovies = await fetch(`${process.env.NEXT_PUBLIC_API_URL}3/movie/top_rated?api_key=${process.env.NEXT_PUBLIC_API_KEY}&language=en-US&page=1`);
  
  const dataLatestMovies = await requestLatestMovies.json();
  const dataPopularMovies = await requestPopularMovies.json();

  console.log(dataLatestMovies);

  console.log("Authored by Chard Reyes");
  return {
      props: {
        popularMovies: dataPopularMovies,
        latestMovies: dataLatestMovies
      },
  }
}
